In [1]:
import numpy as np

# NUMPY

## DAY1

* content
1. 1D 2D 3D array
2. Accessing,Indexing
3. Arange,Random,Reshape

In [ ]:
a=np.array([])   

In [3]:
type(a)

numpy.ndarray

In [4]:
#1D array
b=np.array([1,2,3,4,5,6])

In [5]:
print(b)

[1 2 3 4 5 6]


In [6]:
b

array([1, 2, 3, 4, 5, 6])

In [7]:
type(b)

numpy.ndarray

In [8]:
b.size

6

In [9]:
b.ndim

1

In [10]:
b.shape

(6,)

In [11]:
b.dtype

dtype('int32')

In [12]:
len(b)

6

In [13]:
#2D ARRAY
c=np.array([[11,22,33,44],[10,20,30,40],[100,200,300,400],[55,66,77,88]])

In [14]:
c

array([[ 11,  22,  33,  44],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400],
       [ 55,  66,  77,  88]])

In [15]:
print(c)

[[ 11  22  33  44]
 [ 10  20  30  40]
 [100 200 300 400]
 [ 55  66  77  88]]


In [16]:
c.shape

(4, 4)

In [17]:
c.ndim

2

In [18]:
c.size

16

In [19]:
#3D ARRAY
d=np.array([[[4,40],[3,30],[2,20]],[[11,1],[12,2],[13,3]],[[2,1],[3,2],[4,3]]])

In [20]:
d

array([[[ 4, 40],
        [ 3, 30],
        [ 2, 20]],

       [[11,  1],
        [12,  2],
        [13,  3]],

       [[ 2,  1],
        [ 3,  2],
        [ 4,  3]]])

In [21]:
print(d)

[[[ 4 40]
  [ 3 30]
  [ 2 20]]

 [[11  1]
  [12  2]
  [13  3]]

 [[ 2  1]
  [ 3  2]
  [ 4  3]]]


In [22]:
d.ndim

3

In [23]:
d.shape

(3, 3, 2)

In [24]:
#2D ARRAY INDEXING AND SLICING
c

array([[ 11,  22,  33,  44],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400],
       [ 55,  66,  77,  88]])

In [25]:
c[0,0]

11

In [26]:
c[0]

array([11, 22, 33, 44])

In [27]:
c[2,1]

200

In [28]:
c[3,3]

88

In [29]:
c[-1,-1]

88

In [30]:
c[:,3]

array([ 44,  40, 400,  88])

In [31]:
c[1:3,1:3]

array([[ 20,  30],
       [200, 300]])

In [32]:
#IDENTITY MATRIX
s=np.eye(5)

In [33]:
s

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
#ONES MATRIX
x=np.ones((5,5))

In [35]:
x

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
#ZEROES MATRIX
v=np.zeros((5,5))

In [37]:
v

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
h=np.zeros(1)

In [39]:
h

array([0.])

In [40]:
s.dtype

dtype('float64')

In [41]:
#ARANGE FUNCTION
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [43]:
np.arange(2.5,10.5)

array([2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [44]:
#RESHAPE FUNCTION
b.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.arange(12).reshape(6,2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [46]:
np.arange(12).reshape(2,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [47]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [48]:
#UNKNOWN RESHAPE
np.arange(12).reshape(3,-1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
np.arange(12).reshape(-1,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [50]:
#RANDOM FUNCTION
np.random.rand(5)

array([0.38729847, 0.24695375, 0.22482751, 0.62471044, 0.30823999])

In [51]:
np.random.rand(5,5)

array([[0.9007909 , 0.90939341, 0.97069144, 0.69376783, 0.55654361],
       [0.33106936, 0.54166237, 0.50776331, 0.6450925 , 0.01499938],
       [0.05034681, 0.76681762, 0.27102006, 0.0061095 , 0.95304856],
       [0.48445838, 0.5408057 , 0.38900374, 0.4516206 , 0.39326667],
       [0.66529002, 0.59952443, 0.80206517, 0.76634323, 0.08081004]])

In [52]:
np.random.randn(5)

array([ 0.27283895, -0.72902388,  1.61951464, -0.13942183,  1.178516  ])

In [53]:
np.random.randn(3,3)

array([[-0.05934428,  0.51331905, -0.11067876],
       [ 0.37698958, -0.76380916, -0.53076008],
       [ 0.34594041,  0.61216881,  1.79019159]])

In [54]:
np.random.randint(500,900)

703

In [55]:
np.random.randint(500,900,10)

array([750, 756, 697, 719, 580, 731, 635, 838, 762, 586])

In [56]:
np.random.randint(500,900,12).reshape(4,3)

array([[570, 623, 612],
       [628, 719, 873],
       [617, 536, 762],
       [680, 701, 670]])

In [57]:
#07/07/2022
f=np.array([12,13,1,5,99,6,7])

In [58]:
np.argmax(f)

4

In [59]:
np.argmin(f)

2

In [60]:
np.arange(-1.1,-10.5)

array([], dtype=float64)

In [61]:
np.arange(-1.1,-10.1)

array([], dtype=float64)