# NUMPY

## DAY2

* Agenda
1. argmax,argmin
2. null value creation
3. mathematical operation

In [1]:
import numpy as np

In [2]:
b=np.array([12,23,56,85,20,100,14])

In [3]:
b

array([ 12,  23,  56,  85,  20, 100,  14])

In [4]:
b.ndim

1

## argmax and argmin

In [5]:
np.argmax(b)

5

In [6]:
np.argmin(b)

0

In [7]:
c=np.array([[11,22,33,44],[10,20,30,40],[100,200,300,400],[55,66,77,88]])

In [8]:
c

array([[ 11,  22,  33,  44],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400],
       [ 55,  66,  77,  88]])

In [9]:
np.argmax(c)

11

In [10]:
np.argmin(c)

4

### print(np.argmax(c))
print(np.argmin(c))

## NULL VALUE CREATION

In [15]:
n=np.array([[np.nan,56,10],[56,np.nan,10],[56,10,np.nan]])

In [16]:
n

array([[nan, 56., 10.],
       [56., nan, 10.],
       [56., 10., nan]])

In [17]:
n2=np.array([10,22,33,np.nan,56,77,np.nan,45,89,9,np.nan])

In [18]:
n2

array([10., 22., 33., nan, 56., 77., nan, 45., 89.,  9., nan])

## MATHEMATICAL OPERATIONS

In [19]:
s=np.array([1,2,3,4,5,6])

In [20]:
s

array([1, 2, 3, 4, 5, 6])

In [21]:
s*10

array([10, 20, 30, 40, 50, 60])

In [22]:
s+45

array([46, 47, 48, 49, 50, 51])

In [23]:
1/s

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667])

In [24]:
np.sum(s)

21

In [25]:
c

array([[ 11,  22,  33,  44],
       [ 10,  20,  30,  40],
       [100, 200, 300, 400],
       [ 55,  66,  77,  88]])

In [26]:
n=np.ravel(c)

In [27]:
n.ndim

1

In [28]:
s.mean()

3.5

AttributeError: 'numpy.ndarray' object has no attribute 'median'